;; 设置字体 表格自动对齐
;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
;; sudo pacman -S wqy-zenhei
(set-face-attribute
 'default nil
 :font (font-spec :name "-PfEd-DejaVu Sans Mono-bold-normal-normal-*-*-*-*-*-m-0-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 10.0))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-WenQ-文泉驿等宽正黑-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 12.0)))

;; 中文换行问题
;;(add-hook 'org-mode-hook
;;	  (lambda () (setq truncate-lines nil)))

(provide 'init-font)
